<a href="https://colab.research.google.com/github/MajiroZ/for_git_study/blob/master/Implementation_of_determinant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

##【問題1】行列式を手計算する



A = \begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9
\end{bmatrix}

のi行と

B = \begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1
\end{bmatrix}
のj列のn番目の要素同士の積の和が、行列の積の各要素になる。

C[0,0]（1行目1列目の要素）
C[0,0]=(−1)⋅0+2⋅0+3⋅2=0+0+6=6

C[0,1]（1行目2列目の要素）
C[0,1]=(−1)⋅2+2⋅2+3⋅9=−2+4+27=29

C[0,2]（1行目3列目の要素）
C[0,2]=(−1)⋅1+2⋅(−8)+3⋅(−1)=−1−16−3=−20
他の要素も同様に計算

計算結果をまとめると、行列Cは以下の通り
C = \begin{bmatrix}
6 & 29 & -20\\
12 & 52 & 38\\
-18 & -51 & -48
\end{bmatrix}

##【問題2】NumPyの関数による計算

In [3]:
import numpy as np
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

##【問題3】ある要素の計算を実装

In [6]:
def matrix_product(a, b):
    c = np.zeros((3, 3))
    for i in range(3):
        for j in range(3):
            for k in range(3):
                c[i, j] += a[i, k] * b[k, j]
    return c

In [7]:
matrix_product(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

※3行3列の行列同士の計算用のコードです。

##【問題4】行列積を行う関数の作成

In [12]:
def matrix_product2(a, b):
  c = np.zeros((np.size(a,0), np.size(b,1)))
  for i in range(np.size(a,0)):
    for j in range(np.size(b,1)):
      for k in range(np.size(a,1)):
        c[i, j] += a[i, k] * b[k, j]
  return c

In [13]:
c_ndarray = np.array([[-1, 2, 3, 4], [4, -5, 6, 7], [7, 8, -9, 10]])
d_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1], [1, 2, 3]])
matrix_product2(c_ndarray, d_ndarray)

array([[ 10.,  37.,  -8.],
       [ 19.,  66.,  59.],
       [ -8., -31., -18.]])

##【問題5】計算が定義されない入力を判定する

In [15]:
def matrix_product2(a, b):
  c = np.zeros((np.size(a,0), np.size(b,1)))
  if np.size(a,1) != np.size(b,0):
    print("計算が定義されない行列です。")
  else:
    for i in range(np.size(a,0)):
      for j in range(np.size(b,1)):
        for k in range(np.size(a,1)):
          c[i, j] += a[i, k] * b[k, j]
  return c

In [19]:
d2_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [20]:
matrix_product2(d2_ndarray, e_ndarray)

計算が定義されない行列です。


array([[0., 0., 0.],
       [0., 0., 0.]])

##【問題6】転置

In [22]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# b_ndarrayを転置
b_ndarray_transposed = np.transpose(b_ndarray)

# 行列積を計算
result = np.matmul(a_ndarray, b_ndarray_transposed)

result

array([[  7, -20,  13],
       [ -4, -58, -43],
       [  7,  88,  95]])